### ISSUE TITLE
REQ - Dashboard Development Guidance Feedback

### ISSUE THREAD

**Issue by juliaromero-phs** [Public-Health-Scotland/technical-docs#118]
**Is your feature request related to a problem? Please describe.**
This is general feedback on the Dashboard Development Guidance and Deploying a Shiny App.

**Dashboard Development Guidance**

1. Pros and cons list - can we add open source code in Shiny dashboards as a pro. 
2. User Needs - add some resources for what user stories, user personas and wireframes are? The only "official looking" link I could find came from the UK Government [User Research](https://www.gov.uk/service-manual/user-research). 
3. Accessibility - the guidance will be changing soon as the PHS colour scheme isn't accessible and the accessibility team are working on new guidance with new colours for dashboards. 
4. Monitoring - Could we add a link to how to use Google Analytics with Shiny?

**Deploying a Shiny app**

1. Deploying a Shiny app - Mention that the code mentioned should sit in a separate script and just needs to be ran like a "normal" script to deploy. 
2. Troubleshooting - If dashboard doesn't deploy, Profile code using the [profvis package](https://cran.r-project.org/web/packages/profvis/index.html. )
3. Troubleshooting - If a dashboard is large, and code has been optimised with profiling, the dashboard might need more memory on the Shiny server.

**Comment by rmccreath** [comment]
Issue been applied as feedback to PR
