### ISSUE TITLE
REQ - Guidance on the use of RStudio profiler (`profvis`)

### ISSUE THREAD

**Issue by r6lm** [Public-Health-Scotland/technical-docs#21]
On the [Best Practice with R in Posit Workbench](https://github.com/Public-Health-Scotland/technical-docs/blob/main/Posit%20Infrastructure/Best%20Practice%20with%20R%20in%20Posit%20Workbench.md) document, there is a lot of content on memory efficiency. I believe this can be better tackled if staff are encouraged to use the RStudio integrated profiler, [profvis](http://rstudio.github.io/profvis/index.html).

I would like to submit a pull request modifying the mentioned document, adding succinct guidance, and the link above to `profvis` documentation. 

An alternative would be to create a separate document explaining how to use the integration of `profvis` in RStudio, but I believe with the content available in the package documentation, it is enough.

**Comment by rmccreath** [comment]
Hey @r6lm, I think this makes a lot of sense, please go ahead and submit a pull request if you have ideas to contribute, complete or not as we can contribute further if required. I'm thinking it might be better as additional guidance rather than a replacement but feel free to suggest what you think works! 🎉 
(@terrymclaughlin)

**Comment by r6lm** [comment]
![profiling-pop-up](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/329bfdfd-fd21-487f-9a41-7c64161bd5cb)

**Comment by r6lm** [comment]
![profviz-data-view](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/70f5827e-ce91-43a2-b977-9bef741d9394)

**Comment by r6lm** [comment]
![profviz-flame-graph-view](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/4ccb9c32-fdcb-41a6-b646-86783766be09)
