### ISSUE TITLE
REQ - Change the guidance for opening sessions

### ISSUE THREAD

**Issue by r6lm** [Public-Health-Scotland/technical-docs#58]
The current guidance suggests to open projects in a way that has a lower success rate than the one I am suggesting. The one I am proposing also saves time for the user.

I would like to replace the section of the documentation on how to open sessions, to describe this way of opening sessions — https://github.com/Public-Health-Scotland/technical-docs/blob/main/Posit%20Infrastructure/FAQs.md#how-do-i-open-or-switch-to-another-project.

**Comment by r6lm** [comment]
![2023-10-27-14-34-19-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/4967eda2-f52a-4acd-a04b-5adf6e1e6b92)
![2023-10-27-14-33-48-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/94f82693-97d0-492d-b4ca-12c4bf4a44a5)
![2023-10-27-14-26-46-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/8212b1ce-b297-44d9-ab33-fa2bd838b09c)
![2023-10-27-14-22-03-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/b78bf898-5950-419c-834d-3b02799e6c2e)
![2023-10-30-16-15-01-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/10a70bdc-963c-48f2-b83f-e10e95fe9a13)
![2023-10-27-14-45-27-image](https://github.com/Public-Health-Scotland/technical-docs/assets/46680486/705fc95b-1f32-4b5c-84ce-bcc2fe9073ab)

**Comment by jakeybob** [comment]
Just for info, I've had 100% success this morning using this method... 😃
